name: Run Evaluate Scripts

run-name: Evaluate speed and tempo model against test set

on: [push]

jobs:
  eval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Download test datasets
        run: |
          mkdir -p data
          wget -O data/speed.test.joblib  "https://drive.google.com/uc?export=download&id=1l5l69jijX6ReH5bHNHdsMHSu52Y2l1KZ"
          wget -O data/tempo.test.joblib  "https://drive.google.com/uc?export=download&id=1SX5W-mI8ok5_8AXpUNAEDKiDLhrKrNJy"

      - name: Evaluate speed model
        run: |
          python src/evaluate.py \
            src \
            models/model.speed.joblib \
            data/speed.test.joblib

      - name: Evaluate tempo model
        run: |
          python src/evaluate.py \
            src \
            models/model.tempo.joblib \
            data/tempo.test.joblib